# Streamlit Secrets Configuration Template
# Create a .streamlit/secrets.toml file with the following content:

# Copy this template and create .streamlit/secrets.toml with your actual API keys

[secrets]
VIDEODB_API_KEY = "your_videodb_api_key_here"
GOOGLE_API_KEY = "your_google_genai_api_key_here"

# How to get your API keys:
# 
# 1. VideoDB API Key:
#    - Go to https://console.videodb.io/
#    - Sign up/Sign in
#    - Get your API key from the dashboard
#    - Free for first 50 uploads!
#
# 2. Google GenAI API Key:
#    - Go to https://aistudio.google.com/app/apikey
#    - Create a new API key
#    - Copy the key
#
# IMPORTANT: Never commit your actual API keys to version control!
