# Example secrets.toml file
# Copy this file and rename to secrets.toml, then add your actual API keys

VIDEODB_API_KEY = "sk-2tZQov7tTjsW5uEIdvRk6DA7rcEU9QoBG5m5N6es3Mk"
GOOGLE_API_KEY = "AIzaSyCVpXtOWx6_iq5UvrGOLYVYaglG9UkxC48"
